WeatherForecast.MVC/ViewModels/ForecastIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

using WeatherForecast.Domain; 

namespace WeatherForecast.MVC.ViewModels
{
    public class ForecastIndexViewModel
    {
        [DisplayName("Välj stad:")]
        [Required(ErrorMessage = "Fältet får inte vara tomt - välj stad!")]
        [StringLength(50)]
        public string CityName { get; set; }

        public int counter;

        public bool HasCity
        {
            get { return Citys != null && Citys.Any(); }
        }

        public bool HasForcast
        {
            get { return Forecasts != null && Forecasts.Any(); }
        }

        public string WeekDay(DateTime dateTime, int period)
        {
            var culture = new System.Globalization.CultureInfo("sv-SE");

            if (dateTime.DayOfWeek == DateTime.Now.DayOfWeek && counter != 1)
            {
                counter = 1; 
                return "Idag"; 
               
            }
            if (dateTime.DayOfWeek == DateTime.Now.AddDays(1).DayOfWeek && period == 0)
            {
                return "Imorgon"; 
            }
            if (period == 0) {

                return culture.DateTimeFormat.GetDayName(dateTime.DayOfWeek).ToString();
            }
            else
            {
                return null; 
            }
        }

        public string TimePeriod(DateTime lastUpdate, DateTime nextUpdate)
        {
            string last = lastUpdate.ToString("HH:mm");
            string next = nextUpdate.ToString("HH:mm");

            return last + " - " + next;
        }
        
        public IEnumerable<City> Citys { get; set; }

        public City City { get; set; } 

        public IEnumerable<Forecast> Forecasts { get; set; } 
    }
}

WeatherForecast.MVC/Controllers/ForecastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WeatherForecast.MVC.ViewModels;
using WeatherForecast.Domain;
using WeatherForecast.Domain.Webservices;


namespace WeatherForecast.MVC.Controllers
{
    public class ForecastController : Controller
    {
        private WeatherForecast.Domain.IWeatherForecastService _service;

        public ForecastController()
            : this(new WeatherForecastService())
        {
        }

        public ForecastController(WeatherForecast.Domain.IWeatherForecastService service)
        {
            _service = service;
        }

        // Get: City
        public ActionResult Index()
        {
            return View();
        }

        // Post: City
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "CityName")] ForecastIndexViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Citys = _service.GetCity(model.CityName);
                    if (model.Citys.Count() == 0)
                    {
                        TempData["noCities"] = "Inga städer hittades med namnet " + model.CityName + "!";
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
            }

            return View(model);
        }

        // Get: Weather
        public ActionResult Weather(int id, ForecastIndexViewModel model)
        {
            try
            {
                model.City = _service.FindCity(id);

                if (model.City == null)
                {
                    return View("Error");
                }

                model.Forecasts = _service.GetForecast(model.City);
            }
            catch (Exception)
            {
                return View("Error");
            }

            return View(model); 
        }
	}
}

WeatherForecast.MVC/Views/Forecast/Index.cshtml
@model WeatherForecast.MVC.ViewModels.ForecastIndexViewModel

@{
    ViewBag.Title = "Väder prognos";
}

<h1>Väder prognos!</h1>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, String.Empty, new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, String.Empty, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Sök" class="btn btn-primary btn-sm" />
            </div>
        </div>
    </div>
}

<p class="error">@TempData["noCities"]</p>

@if (Model != null && Model.HasCity)
{
    <ul id="citys">
        @Html.DisplayFor(m => m.Citys)
    </ul>
}

WeatherForecast.MVC/Views/Forecast/Weather.cshtml
@model WeatherForecast.MVC.ViewModels.ForecastIndexViewModel

@{
    ViewBag.Title = "Väder prognos";
}

<br />
<br />

@Html.ActionLink("Tillbaka - Sök efter ny stad!", "Index")

<h2>Väder prognos för @Model.City.Name</h2>

<br />

@if (Model != null && Model.HasForcast)
{
    foreach (var item in @Model.Forecasts)
    {
        var day = Model.WeekDay(item.NextUpdate, item.Period);

        if (day != null)
        {
            <h3>@day</h3>
        }
        
        <p>@Model.TimePeriod(item.LastUpdate, item.NextUpdate)
        <span class="weatherSymbol"><img src="http://api.yr.no/weatherapi/weathericon/1.1/?symbol=@item.Symbol;content_type=image/png" /></span>
        <span class="temp">@item.Temperature &deg;C</span>      
        </p>
    }
}

WeatherForecast.MVC/Views/Shared/DisplayTemplates/City.cshtml
<li>  
    @Html.ActionLink((string)Model.Name, "Weather", new { city = @Model.Name, region = @Model.Region, country = @Model.Country, id = @Model.CityID}), @Model.Region, @Model.Country
</li>

WeatherForecast.MVC/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Page Not Found";
}

<h1>Page Not Found</h1>

<p>Sidan kunde inte hittas, fel i url!</p>

@Html.ActionLink("Tillbaks till startsidan!", "Index", "Forecast")

@* Error page must be longer than 512 bytes for IE and Chrome to show it. 
   So add padding in case we're short. *@
@(new string(' ', 512))

WeatherForecast.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/simple-css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Annie Sahlberg</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>